### ISSUE TITLE
Model constructor should have an $attributes parameter

### ISSUE THREAD

**Issue by FrancisMawn** [repat/laravel-job-models#3]
Hi,

Your models override their constructors, but they're not defining the $attributes parameter in the signature, which makes it impossible to create a factory for them.

Your constructors should be defined like that:
```php
public function __construct(array $attributes = [])
{
    parent::__construct($attributes);
    $this->table = Config::get('queue.failed.table', 'job_fails');
}
```

**Comment by repat** [comment]
Usually I'd say you've found yourself an open source task ;) But this was an easy fix: https://github.com/repat/laravel-job-models/releases/tag/0.7

Thanks!
